branches:
  only:
  - main
language: node_js
node_js: node
cache:
  directories:
  - node_modules
install:
- yarn
- yarn build
script:
- echo "Skipping tests"
deploy:
  provider: heroku
  skip-cleanup: true
  app: chatbot-wars
  github-token: "$GITHUB_TOKEN"
  target-branch: prod
  local-dir: dist
  on:
    branch: prod
dd:
  secure: rn5k9Zz6uXtPWYUvt23gdRlgRe5gOSYQ2u7OU4ddIoTir8re7Yzz6DUuAL8eIFpruI5HHMPoEGYAyhz+FavTwNaSfpscSJtxDiNpCB8u0tVD/SmrD9fEvb4M1zhORd7MwlW+Mg57KfUBjGUxvY23AWsuuXb42Xe2XZYg4YAziRWm+9xwlN5JwPiBR29nJ81cg8XcuAZRFCSjGxkCRQrpoTj2oPGvsTJNMVsdDfzYIIVVT8rs9JqzMC8XCO8RYILWqiZ0qnNNQvibWooUwNd/E4DE5sKy+H+qUXhe5bxHkObgTWRZncFSpiUGSTF6uZLA30kb9s7FHXDn+jio0Mdx2UW4E92DQpvCiNxJLix/Xzn7aIZkdIBvszWtTG2/YV3DiHYCK2AG9ONJehbQV6Yh0HVvxRGmPQAXGMbmmRwt6LZLAMN+zGrJldb0CBFkivyTIMuQh1GqaZascMR4AVFgfBDdG2neJroUjE+p9qWI1DwIMa98hvA4Jv/+MTD05LUBAplFu+nFvKqa9NNDrLOL55muOsddVD2Tmu4KC0ON1LmerUkt/aLZQlO9ZHeljNBtuJFha+iUqYOZxeq4Fr0DGtW1dqmZ9XnZ3TlOoYTf2IsveX5RnZ0sDdyfjCq40zV4fGlvZwvLRHmTrAQQvcw4MBiEP2lhW3r4VnI4hxrg1ZE=
